export interface Surah {
  /** Surah number, 1–114 */
  number: number;
  /** Arabic name */
  nameAr: string;
  /** Latin transliteration, for search/debugging */
  nameTransliterated: string;
  /** Number of ayahs in the surah (standard Mushaf al-Madinah count) */
  ayahCount: number;
}

// Standard 114-surah reference table (Mushaf al-Madinah / King Fahd Complex ayah counts).
// NOTE: verify against a printed Mushaf before relying on this for anything beyond UI range
// selection — a single miscount here would silently mis-bound the ayah picker.
export const SURAHS: Surah[] = [
  { number: 1, nameAr: 'الفاتحة', nameTransliterated: 'Al-Fatihah', ayahCount: 7 },
  { number: 2, nameAr: 'البقرة', nameTransliterated: 'Al-Baqarah', ayahCount: 286 },
  { number: 3, nameAr: 'آل عمران', nameTransliterated: 'Aal-E-Imran', ayahCount: 200 },
  { number: 4, nameAr: 'النساء', nameTransliterated: 'An-Nisa', ayahCount: 176 },
  { number: 5, nameAr: 'المائدة', nameTransliterated: "Al-Ma'idah", ayahCount: 120 },
  { number: 6, nameAr: 'الأنعام', nameTransliterated: "Al-An'am", ayahCount: 165 },
  { number: 7, nameAr: 'الأعراف', nameTransliterated: "Al-A'raf", ayahCount: 206 },
  { number: 8, nameAr: 'الأنفال', nameTransliterated: 'Al-Anfal', ayahCount: 75 },
  { number: 9, nameAr: 'التوبة', nameTransliterated: 'At-Tawbah', ayahCount: 129 },
  { number: 10, nameAr: 'يونس', nameTransliterated: 'Yunus', ayahCount: 109 },
  { number: 11, nameAr: 'هود', nameTransliterated: 'Hud', ayahCount: 123 },
  { number: 12, nameAr: 'يوسف', nameTransliterated: 'Yusuf', ayahCount: 111 },
  { number: 13, nameAr: 'الرعد', nameTransliterated: "Ar-Ra'd", ayahCount: 43 },
  { number: 14, nameAr: 'إبراهيم', nameTransliterated: 'Ibrahim', ayahCount: 52 },
  { number: 15, nameAr: 'الحجر', nameTransliterated: 'Al-Hijr', ayahCount: 99 },
  { number: 16, nameAr: 'النحل', nameTransliterated: 'An-Nahl', ayahCount: 128 },
  { number: 17, nameAr: 'الإسراء', nameTransliterated: 'Al-Isra', ayahCount: 111 },
  { number: 18, nameAr: 'الكهف', nameTransliterated: 'Al-Kahf', ayahCount: 110 },
  { number: 19, nameAr: 'مريم', nameTransliterated: 'Maryam', ayahCount: 98 },
  { number: 20, nameAr: 'طه', nameTransliterated: 'Ta-Ha', ayahCount: 135 },
  { number: 21, nameAr: 'الأنبياء', nameTransliterated: 'Al-Anbiya', ayahCount: 112 },
  { number: 22, nameAr: 'الحج', nameTransliterated: 'Al-Hajj', ayahCount: 78 },
  { number: 23, nameAr: 'المؤمنون', nameTransliterated: "Al-Mu'minun", ayahCount: 118 },
  { number: 24, nameAr: 'النور', nameTransliterated: 'An-Nur', ayahCount: 64 },
  { number: 25, nameAr: 'الفرقان', nameTransliterated: 'Al-Furqan', ayahCount: 77 },
  { number: 26, nameAr: 'الشعراء', nameTransliterated: "Ash-Shu'ara", ayahCount: 227 },
  { number: 27, nameAr: 'النمل', nameTransliterated: 'An-Naml', ayahCount: 93 },
  { number: 28, nameAr: 'القصص', nameTransliterated: 'Al-Qasas', ayahCount: 88 },
  { number: 29, nameAr: 'العنكبوت', nameTransliterated: 'Al-Ankabut', ayahCount: 69 },
  { number: 30, nameAr: 'الروم', nameTransliterated: 'Ar-Rum', ayahCount: 60 },
  { number: 31, nameAr: 'لقمان', nameTransliterated: 'Luqman', ayahCount: 34 },
  { number: 32, nameAr: 'السجدة', nameTransliterated: 'As-Sajdah', ayahCount: 30 },
  { number: 33, nameAr: 'الأحزاب', nameTransliterated: 'Al-Ahzab', ayahCount: 73 },
  { number: 34, nameAr: 'سبأ', nameTransliterated: 'Saba', ayahCount: 54 },
  { number: 35, nameAr: 'فاطر', nameTransliterated: 'Fatir', ayahCount: 45 },
  { number: 36, nameAr: 'يس', nameTransliterated: 'Ya-Sin', ayahCount: 83 },
  { number: 37, nameAr: 'الصافات', nameTransliterated: 'As-Saffat', ayahCount: 182 },
  { number: 38, nameAr: 'ص', nameTransliterated: 'Sad', ayahCount: 88 },
  { number: 39, nameAr: 'الزمر', nameTransliterated: 'Az-Zumar', ayahCount: 75 },
  { number: 40, nameAr: 'غافر', nameTransliterated: 'Ghafir', ayahCount: 85 },
  { number: 41, nameAr: 'فصلت', nameTransliterated: 'Fussilat', ayahCount: 54 },
  { number: 42, nameAr: 'الشورى', nameTransliterated: 'Ash-Shura', ayahCount: 53 },
  { number: 43, nameAr: 'الزخرف', nameTransliterated: 'Az-Zukhruf', ayahCount: 89 },
  { number: 44, nameAr: 'الدخان', nameTransliterated: 'Ad-Dukhan', ayahCount: 59 },
  { number: 45, nameAr: 'الجاثية', nameTransliterated: 'Al-Jathiyah', ayahCount: 37 },
  { number: 46, nameAr: 'الأحقاف', nameTransliterated: 'Al-Ahqaf', ayahCount: 35 },
  { number: 47, nameAr: 'محمد', nameTransliterated: 'Muhammad', ayahCount: 38 },
  { number: 48, nameAr: 'الفتح', nameTransliterated: 'Al-Fath', ayahCount: 29 },
  { number: 49, nameAr: 'الحجرات', nameTransliterated: 'Al-Hujurat', ayahCount: 18 },
  { number: 50, nameAr: 'ق', nameTransliterated: 'Qaf', ayahCount: 45 },
  { number: 51, nameAr: 'الذاريات', nameTransliterated: 'Adh-Dhariyat', ayahCount: 60 },
  { number: 52, nameAr: 'الطور', nameTransliterated: 'At-Tur', ayahCount: 49 },
  { number: 53, nameAr: 'النجم', nameTransliterated: 'An-Najm', ayahCount: 62 },
  { number: 54, nameAr: 'القمر', nameTransliterated: 'Al-Qamar', ayahCount: 55 },
  { number: 55, nameAr: 'الرحمن', nameTransliterated: 'Ar-Rahman', ayahCount: 78 },
  { number: 56, nameAr: 'الواقعة', nameTransliterated: "Al-Waqi'ah", ayahCount: 96 },
  { number: 57, nameAr: 'الحديد', nameTransliterated: 'Al-Hadid', ayahCount: 29 },
  { number: 58, nameAr: 'المجادلة', nameTransliterated: 'Al-Mujadilah', ayahCount: 22 },
  { number: 59, nameAr: 'الحشر', nameTransliterated: 'Al-Hashr', ayahCount: 24 },
  { number: 60, nameAr: 'الممتحنة', nameTransliterated: 'Al-Mumtahanah', ayahCount: 13 },
  { number: 61, nameAr: 'الصف', nameTransliterated: 'As-Saff', ayahCount: 14 },
  { number: 62, nameAr: 'الجمعة', nameTransliterated: "Al-Jumu'ah", ayahCount: 11 },
  { number: 63, nameAr: 'المنافقون', nameTransliterated: 'Al-Munafiqun', ayahCount: 11 },
  { number: 64, nameAr: 'التغابن', nameTransliterated: 'At-Taghabun', ayahCount: 18 },
  { number: 65, nameAr: 'الطلاق', nameTransliterated: 'At-Talaq', ayahCount: 12 },
  { number: 66, nameAr: 'التحريم', nameTransliterated: 'At-Tahrim', ayahCount: 12 },
  { number: 67, nameAr: 'الملك', nameTransliterated: 'Al-Mulk', ayahCount: 30 },
  { number: 68, nameAr: 'القلم', nameTransliterated: 'Al-Qalam', ayahCount: 52 },
  { number: 69, nameAr: 'الحاقة', nameTransliterated: 'Al-Haqqah', ayahCount: 52 },
  { number: 70, nameAr: 'المعارج', nameTransliterated: "Al-Ma'arij", ayahCount: 44 },
  { number: 71, nameAr: 'نوح', nameTransliterated: 'Nuh', ayahCount: 28 },
  { number: 72, nameAr: 'الجن', nameTransliterated: 'Al-Jinn', ayahCount: 28 },
  { number: 73, nameAr: 'المزمل', nameTransliterated: 'Al-Muzzammil', ayahCount: 20 },
  { number: 74, nameAr: 'المدثر', nameTransliterated: 'Al-Muddaththir', ayahCount: 56 },
  { number: 75, nameAr: 'القيامة', nameTransliterated: 'Al-Qiyamah', ayahCount: 40 },
  { number: 76, nameAr: 'الإنسان', nameTransliterated: 'Al-Insan', ayahCount: 31 },
  { number: 77, nameAr: 'المرسلات', nameTransliterated: 'Al-Mursalat', ayahCount: 50 },
  { number: 78, nameAr: 'النبأ', nameTransliterated: 'An-Naba', ayahCount: 40 },
  { number: 79, nameAr: 'النازعات', nameTransliterated: "An-Nazi'at", ayahCount: 46 },
  { number: 80, nameAr: 'عبس', nameTransliterated: 'Abasa', ayahCount: 42 },
  { number: 81, nameAr: 'التكوير', nameTransliterated: 'At-Takwir', ayahCount: 29 },
  { number: 82, nameAr: 'الانفطار', nameTransliterated: 'Al-Infitar', ayahCount: 19 },
  { number: 83, nameAr: 'المطففين', nameTransliterated: 'Al-Mutaffifin', ayahCount: 36 },
  { number: 84, nameAr: 'الانشقاق', nameTransliterated: 'Al-Inshiqaq', ayahCount: 25 },
  { number: 85, nameAr: 'البروج', nameTransliterated: 'Al-Buruj', ayahCount: 22 },
  { number: 86, nameAr: 'الطارق', nameTransliterated: 'At-Tariq', ayahCount: 17 },
  { number: 87, nameAr: 'الأعلى', nameTransliterated: "Al-A'la", ayahCount: 19 },
  { number: 88, nameAr: 'الغاشية', nameTransliterated: 'Al-Ghashiyah', ayahCount: 26 },
  { number: 89, nameAr: 'الفجر', nameTransliterated: 'Al-Fajr', ayahCount: 30 },
  { number: 90, nameAr: 'البلد', nameTransliterated: 'Al-Balad', ayahCount: 20 },
  { number: 91, nameAr: 'الشمس', nameTransliterated: 'Ash-Shams', ayahCount: 15 },
  { number: 92, nameAr: 'الليل', nameTransliterated: 'Al-Layl', ayahCount: 21 },
  { number: 93, nameAr: 'الضحى', nameTransliterated: 'Ad-Duha', ayahCount: 11 },
  { number: 94, nameAr: 'الشرح', nameTransliterated: 'Ash-Sharh', ayahCount: 8 },
  { number: 95, nameAr: 'التين', nameTransliterated: 'At-Tin', ayahCount: 8 },
  { number: 96, nameAr: 'العلق', nameTransliterated: 'Al-Alaq', ayahCount: 19 },
  { number: 97, nameAr: 'القدر', nameTransliterated: 'Al-Qadr', ayahCount: 5 },
  { number: 98, nameAr: 'البينة', nameTransliterated: 'Al-Bayyinah', ayahCount: 8 },
  { number: 99, nameAr: 'الزلزلة', nameTransliterated: 'Az-Zalzalah', ayahCount: 8 },
  { number: 100, nameAr: 'العاديات', nameTransliterated: 'Al-Adiyat', ayahCount: 11 },
  { number: 101, nameAr: 'القارعة', nameTransliterated: "Al-Qari'ah", ayahCount: 11 },
  { number: 102, nameAr: 'التكاثر', nameTransliterated: 'At-Takathur', ayahCount: 8 },
  { number: 103, nameAr: 'العصر', nameTransliterated: 'Al-Asr', ayahCount: 3 },
  { number: 104, nameAr: 'الهمزة', nameTransliterated: 'Al-Humazah', ayahCount: 9 },
  { number: 105, nameAr: 'الفيل', nameTransliterated: 'Al-Fil', ayahCount: 5 },
  { number: 106, nameAr: 'قريش', nameTransliterated: 'Quraysh', ayahCount: 4 },
  { number: 107, nameAr: 'الماعون', nameTransliterated: "Al-Ma'un", ayahCount: 7 },
  { number: 108, nameAr: 'الكوثر', nameTransliterated: 'Al-Kawthar', ayahCount: 3 },
  { number: 109, nameAr: 'الكافرون', nameTransliterated: 'Al-Kafirun', ayahCount: 6 },
  { number: 110, nameAr: 'النصر', nameTransliterated: 'An-Nasr', ayahCount: 3 },
  { number: 111, nameAr: 'المسد', nameTransliterated: 'Al-Masad', ayahCount: 5 },
  { number: 112, nameAr: 'الإخلاص', nameTransliterated: 'Al-Ikhlas', ayahCount: 4 },
  { number: 113, nameAr: 'الفلق', nameTransliterated: 'Al-Falaq', ayahCount: 5 },
  { number: 114, nameAr: 'الناس', nameTransliterated: 'An-Nas', ayahCount: 6 },
];
